version: "3"
services:
  web:
    build:
      context: .
      dockerfile: ./infra/docker/web/Dockerfile
    ports:
      - 8080:80
    volumes:
      - ./mail-form:/var/www/mail-form

  mysql:
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mysql
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      TZ: Asia/Tokyo
    networks:
      - app-net

  phpmyadmin:
    image: phpmyadmin
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
    ports:
      - 8045:80
    networks:
      - app-net

  mail:
    image: mailhog/mailhog:latest
    ports:
      - 8025:8025
      - 1025:1025
    networks:
      - app-net

networks:
    app-net:
      driver: bridge